all: task2

task2: start.o util.o main.o
	ld -m elf_i386 start.o util.o main.o -o task2

start.o: start.s
	nasm -f elf32 start.s -o start.o	

util.o: util.c
	gcc -m32 -Wall -ansi -c -nostdlib -fno-stack-protector util.c -o util.o	

main.o:
	gcc -m32 -Wall -ansi -c -nostdlib -fno-stack-protector main.c -o main.o	

clean:
	rm -f start.o util.o task2 main.o	